AWS_ACCESS_KEY_ID = "access_key_id"
AWS_SECRET_ACCESS_KEY = "secret_access_key"
SECRET_ID = "secret_id"
ERROR_SECRET_ID_NOT_FOUND = "Secret id is not found from secret_reference_metadata"
INVALID_JSON_FORMAT_ERROR = "Invalid JSON format for secret_value"
INVALID_VAULT_URL_ERROR = "Invalid Vault URL. Missing {} in the URL"